# Use postgres/example user/password credentials

services:

  postgres:
    image: postgres:16.3-alpine3.19
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: bounca
      POSTGRES_PASSWORD: changeit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bounca:
    build:
      context: .
    image: bounca:latest
    container_name: bounca
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
